---
version: "2.1"
services:
  shorturl:
    image: nicholaswilde/shorturl:latest
    container_name: shorturl-default
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - app:/app
      - data:/data
volumes:
  app:
  data:
