---
name: Goss

on:
  workflow_dispatch:

env:
  # How long to sleep before running the tests (gives the application time to start)
  GOSS_SLEEP: 30

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64

    # Install and configure Buildx
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:latest

    # Install the GOSS testing framework
    - name: Set up goss/dgoss
      uses: e1himself/goss-installation-action@v1.0.3
      if: ${{ steps.prep.outputs.goss == 'true' }}
      with:
        version: 'v0.3.16'

    # Creates a local build to run tests on
    - name: Build and Load local test-container
      uses: docker/build-push-action@v2
      with:
        build-args: VERSION=v0.1.0
        context: .
        file: ./Dockerfile
        load: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/shorturl:test

    # Run GOSS tests if included with the container
    - name: Run GOSS tests
      env:
        GOSS_FILE: ./goss.yaml
      run: |
        dgoss run ghcr.io/${{ github.repository_owner }}/shorturl:test
